### ISSUE TITLE
Add an option for dumping into a file

### ISSUE THREAD

**Issue by B-G-T** [maehw/snowbirdopter#8]
It would be helpful to have the possibility to dump data directly into a binary file.

**Comment by maehw** [comment]
That should already work. Have a look at the `-f <filename>` command line option. It should work in both directions for dump and (up)load/exec(ution). Though, documentation might still lack this information.

**Comment by maehw** [comment]
Yes, should work. Try loading something and reading it back - then compare the binaries:

```
$ python3 ../../../snowbirdopter.py -c load -a 08010000 -p /dev/tty.SLAB_USBtoUART -f out.bin -v 2
$ python3 ../../../snowbirdopter.py -c dump -a 08010000 -e 080102c1 -p /dev/tty.SLAB_USBtoUART -v 1 -f out_readback.bin
```
